# Generated by Django 2.1.2 on 2018-10-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='attachment',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='promise',
            field=models.TextField(default='money'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='deadline',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
